In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import copy
from scipy import stats
%matplotlib inline

In [ ]:
#Algoritma Paketleri#
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import statsmodels.api as sm
from scipy import stats
%matplotlib inline
import warnings
from sklearn import model_selection
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestClassifier
from math import sqrt
import math
from matplotlib import pyplot
from sklearn.utils import resample
warnings.filterwarnings('ignore')
from sklearn.metrics import confusion_matrix as cm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.feature_selection import RFE
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from ipywidgets import Image
from io import StringIO
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeClassifier
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
!pip install pydotplus
import pydotplus
!pip install graphviz
from IPython.display import SVG
from graphviz import Source
from IPython.display import display
from sklearn import tree
from sklearn import ensemble
from sklearn.metrics import precision_recall_curve
from IPython.display import Image
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
!pip install xgboost
!pip install lightgbm
!pip install catboost
from sklearn.cluster import KMeans
from catboost import CatBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn import linear_model
from sklearn.model_selection import GridSearchCV, cross_val_score, learning_curve
from sklearn.model_selection import cross_val_predict
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, cross_val_score, learning_curve
from sklearn.model_selection import cross_val_predict
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
from sklearn.feature_selection import RFECV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from catboost import CatBoostRegressor
from sklearn import decomposition, datasets
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.ensemble import GradientBoostingRegressor
from scipy.stats import randint
from sklearn.cluster import KMeans
from scipy.cluster.hierarchy import linkage
from scipy.cluster.hierarchy import fcluster
from sklearn.manifold import TSNE
from sklearn.metrics import make_scorer

In [3]:
df = pd.read_csv("Desktop/AI_Works/Kaggle/Tabular/train.csv")

In [4]:
df.shape

(4000000, 56)

In [5]:
df.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,0,3189,40,8,30,13,3270,206,234,193,...,0,0,0,0,0,0,0,0,0,1
1,1,3026,182,5,280,29,3270,233,240,106,...,0,0,0,0,0,0,0,0,0,2
2,2,3106,13,7,351,37,2914,208,234,137,...,0,0,0,0,0,0,0,0,0,1
3,3,3022,276,13,192,16,3034,207,238,156,...,0,0,0,0,0,0,0,0,0,2
4,4,2906,186,13,266,22,2916,231,231,154,...,0,0,0,0,0,0,0,0,0,2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000000 entries, 0 to 3999999
Data columns (total 56 columns):
 #   Column                              Dtype
---  ------                              -----
 0   Id                                  int64
 1   Elevation                           int64
 2   Aspect                              int64
 3   Slope                               int64
 4   Horizontal_Distance_To_Hydrology    int64
 5   Vertical_Distance_To_Hydrology      int64
 6   Horizontal_Distance_To_Roadways     int64
 7   Hillshade_9am                       int64
 8   Hillshade_Noon                      int64
 9   Hillshade_3pm                       int64
 10  Horizontal_Distance_To_Fire_Points  int64
 11  Wilderness_Area1                    int64
 12  Wilderness_Area2                    int64
 13  Wilderness_Area3                    int64
 14  Wilderness_Area4                    int64
 15  Soil_Type1                          int64
 16  Soil_Type2                          int64
 17  Soil_Type3                          int64
 18  Soil_Type4                          int64
 19  Soil_Type5                          int64
 20  Soil_Type6                          int64
 21  Soil_Type7                          int64
 22  Soil_Type8                          int64
 23  Soil_Type9                          int64
 24  Soil_Type10                         int64
 25  Soil_Type11                         int64
 26  Soil_Type12                         int64
 27  Soil_Type13                         int64
 28  Soil_Type14                         int64
 29  Soil_Type15                         int64
 30  Soil_Type16                         int64
 31  Soil_Type17                         int64
 32  Soil_Type18                         int64
 33  Soil_Type19                         int64
 34  Soil_Type20                         int64
 35  Soil_Type21                         int64
 36  Soil_Type22                         int64
 37  Soil_Type23                         int64
 38  Soil_Type24                         int64
 39  Soil_Type25                         int64
 40  Soil_Type26                         int64
 41  Soil_Type27                         int64
 42  Soil_Type28                         int64
 43  Soil_Type29                         int64
 44  Soil_Type30                         int64
 45  Soil_Type31                         int64
 46  Soil_Type32                         int64
 47  Soil_Type33                         int64
 48  Soil_Type34                         int64
 49  Soil_Type35                         int64
 50  Soil_Type36                         int64
 51  Soil_Type37                         int64
 52  Soil_Type38                         int64
 53  Soil_Type39                         int64
 54  Soil_Type40                         int64
 55  Cover_Type                          int64
dtypes: int64(56)
memory usage: 1.7 GB

In [7]:
df.describe().astype("int")

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
count,4000000,4000000,4000000,4000000,4000000,4000000,4000000,4000000,4000000,4000000,...,4000000,4000000,4000000,4000000,4000000,4000000,4000000,4000000,4000000,4000000
mean,1999999,2980,151,15,271,51,1766,211,221,140,...,0,0,0,0,0,0,0,0,0,1
std,1154700,289,109,8,226,68,1315,30,22,43,...,0,0,0,0,0,0,0,0,0,0
min,0,1773,-33,-3,-92,-317,-287,-4,49,-53,...,0,0,0,0,0,0,0,0,0,1
25%,999999,2760,60,9,110,4,822,198,210,115,...,0,0,0,0,0,0,0,0,0,1
50%,1999999,2966,123,14,213,31,1436,218,224,142,...,0,0,0,0,0,0,0,0,0,2
75%,2999999,3217,247,20,361,78,2365,233,237,169,...,0,0,0,0,0,0,0,0,0,2
max,3999999,4383,407,64,1602,647,7666,301,279,272,...,1,1,1,1,1,1,1,1,1,7

In [8]:
#I WILL RUN ML MODELS ON 4 DIFFERENT FEATURE SUBSETS

#1-NORMAL(AS THE FEATURES ARE GIVEN, NOTHING IS CHANGED)
#2-STANDARD SCALED
#3-NORMAL SCALED
#4-AFTER NORMALIZATION AND FEATURE SELECTION PROCESSES
#5-DO HYPER PARAMETER SELECTION BY USING THE BEST SUBSET&MODEL

In [9]:
(df.Cover_Type.value_counts(normalize=True)*100).astype("int")

2    56
1    36
3     4
7     1
6     0
4     0
5     0
Name: Cover_Type, dtype: int64

In [10]:
x = df.loc[:, df.columns!='Cover_Type']

In [11]:
x.drop(columns=["Id"],inplace=True)

In [12]:
y = df[["Cover_Type"]]

In [13]:
x.shape

(4000000, 54)

In [14]:
y.shape

(4000000, 1)

In [217]:
#1-NORMAL(AS THE FEATURES ARE GIVEN, NOTHING IS CHANGED)

In [218]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2021)

In [219]:
#Logistic Regression
lm = LogisticRegression()
lm.fit(x_train, y_train)
y_pred = lm.predict(x_test)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.5363567358756958

              precision    recall  f1-score   support

           1       0.47      0.25      0.33    440454
           2       0.58      0.82      0.68    678495
           3       0.77      0.03      0.06     58765
           4       0.00      0.00      0.00       110
           6       0.00      0.00      0.00      3437
           7       0.00      0.00      0.00     18739

    accuracy                           0.56   1200000
   macro avg       0.30      0.18      0.18   1200000
weighted avg       0.54      0.56      0.51   1200000

In [220]:
#Decision Tree#
clf = DecisionTreeClassifier()
clf = clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.9418079434063695

              precision    recall  f1-score   support

           1       0.94      0.94      0.94    440454
           2       0.96      0.96      0.96    678495
           3       0.83      0.84      0.84     58765
           4       0.23      0.25      0.23       110
           6       0.49      0.50      0.50      3437
           7       0.72      0.72      0.72     18739

    accuracy                           0.94   1200000
   macro avg       0.69      0.70      0.70   1200000
weighted avg       0.94      0.94      0.94   1200000

In [221]:
#Random Forest
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.9551401982535045

              precision    recall  f1-score   support

           1       0.95      0.96      0.96    440454
           2       0.96      0.97      0.97    678495
           3       0.91      0.84      0.87     58765
           4       0.75      0.03      0.05       110
           6       0.80      0.28      0.42      3437
           7       0.90      0.58      0.71     18739

    accuracy                           0.96   1200000
   macro avg       0.88      0.61      0.66   1200000
weighted avg       0.96      0.96      0.95   1200000

In [222]:
#AdaBoost#
AdaBoost = AdaBoostClassifier()
AdaBoost.fit(x_train,y_train)
y_pred=AdaBoost.predict(x_test)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.8156330206141489

              precision    recall  f1-score   support

           1       0.85      0.97      0.91    440454
           2       0.89      0.92      0.90    678495
           3       0.00      0.00      0.00     58765
           4       0.00      0.00      0.00       110
           6       0.00      0.00      0.00      3437
           7       0.00      0.00      0.00     18739

    accuracy                           0.87   1200000
   macro avg       0.29      0.31      0.30   1200000
weighted avg       0.82      0.87      0.84   1200000

In [223]:
#2-STANDARD SCALED

In [224]:
#Let's start with Standardization

In [225]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2021)

In [226]:
from sklearn.preprocessing import StandardScaler

In [227]:
x.drop(columns=["Id"],inplace=True)

In [228]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2021)

In [229]:
standard_scaler = StandardScaler().fit(x_train)

In [230]:
x_train_scale = standard_scaler.transform(x_train)
x_train_scale = pd.DataFrame(x_train_scale, columns= x.columns)
print(x_train_scale.shape)
x_train_scale.head()

(2800000, 54)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,0.891534,-0.877831,-0.362642,-0.292574,0.166649,-0.085948,0.233007,0.626759,0.919316,0.780481,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864
1,-0.191106,-1.278024,-0.947704,-0.650170,0.943800,-0.139902,0.980243,-0.362936,-1.323418,-1.046736,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864
2,-0.388264,-1.087023,-0.011605,-0.036518,0.371934,1.470337,1.435083,-0.003047,-0.797062,-0.428798,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,4.952563,-0.180864
3,-0.101174,-0.741402,0.105408,-0.376454,-0.302574,-0.050233,-2.463542,-0.497894,-1.735349,0.508304,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,4.952563,-0.180864
4,-0.004325,0.186317,2.094618,1.702898,-0.287911,-0.530493,1.207663,-1.352630,2.017798,-0.231094,...,-0.168369,5.063148,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,4.952563,-0.180864

In [231]:
x_test_scale = standard_scaler.transform(x_test)
x_test_scale = pd.DataFrame(x_test_scale, columns= x.columns)
print(x_test_scale.shape)
x_test_scale.head()

(1200000, 54)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,-0.917478,-0.968784,0.690469,-0.734050,1.676961,-1.377027,0.622869,-1.577561,0.072569,-0.859671,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864
1,1.016055,-0.686830,-0.947704,-0.319062,-0.478533,-0.196135,1.012732,-0.272964,-0.476672,-0.286061,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,4.952563,-0.180864
2,-1.263369,1.641562,-1.064716,-0.063006,-0.786460,1.146618,0.233007,-0.452908,2.063568,-0.308225,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864
3,-0.806793,1.723420,-0.947704,-1.113720,-0.801123,-0.234130,-1.813772,-0.182991,0.759121,0.584549,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864
4,0.075230,-0.568592,-0.128617,-0.517727,-0.111952,-0.726548,0.525404,-0.003047,0.118339,2.400241,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864

In [232]:
#Logistic Regression
lm = LogisticRegression()
lm.fit(x_train_scale, y_train)
y_pred = lm.predict(x_test_scale)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.9118992093677225

              precision    recall  f1-score   support

           1       0.90      0.92      0.91    440454
           2       0.94      0.95      0.94    678495
           3       0.85      0.81      0.83     58765
           4       0.00      0.00      0.00       110
           6       0.38      0.16      0.23      3437
           7       0.50      0.21      0.30     18739

    accuracy                           0.92   1200000
   macro avg       0.59      0.51      0.54   1200000
weighted avg       0.91      0.92      0.91   1200000

In [233]:
#Decision Tree#
clf = DecisionTreeClassifier()
clf = clf.fit(x_train_scale,y_train)
y_pred = clf.predict(x_test_scale)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.9424812430993237

              precision    recall  f1-score   support

           1       0.95      0.94      0.94    440454
           2       0.96      0.96      0.96    678495
           3       0.83      0.85      0.84     58765
           4       0.20      0.25      0.22       110
           6       0.51      0.52      0.51      3437
           7       0.72      0.72      0.72     18739

    accuracy                           0.94   1200000
   macro avg       0.69      0.71      0.70   1200000
weighted avg       0.94      0.94      0.94   1200000

In [234]:
#Random Forest
rf = RandomForestClassifier()
rf.fit(x_train_scale, y_train)
y_pred = rf.predict(x_test_scale)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.956322794269219

              precision    recall  f1-score   support

           1       0.95      0.96      0.96    440454
           2       0.97      0.97      0.97    678495
           3       0.90      0.85      0.88     58765
           4       0.75      0.03      0.05       110
           6       0.80      0.31      0.45      3437
           7       0.90      0.61      0.72     18739

    accuracy                           0.96   1200000
   macro avg       0.88      0.62      0.67   1200000
weighted avg       0.96      0.96      0.96   1200000

In [235]:
#AdaBoost#
AdaBoost = AdaBoostClassifier()
AdaBoost.fit(x_train_scale,y_train)
y_pred=AdaBoost.predict(x_test_scale)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.8156330206141489

              precision    recall  f1-score   support

           1       0.85      0.97      0.91    440454
           2       0.89      0.92      0.90    678495
           3       0.00      0.00      0.00     58765
           4       0.00      0.00      0.00       110
           6       0.00      0.00      0.00      3437
           7       0.00      0.00      0.00     18739

    accuracy                           0.87   1200000
   macro avg       0.29      0.31      0.30   1200000
weighted avg       0.82      0.87      0.84   1200000

In [236]:
#3-NORMAL SCALED

In [237]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2021)

In [238]:
from sklearn.preprocessing import MinMaxScaler

In [239]:
minmax_scaler = MinMaxScaler().fit(x_train)

In [240]:
x_train_scale = minmax_scaler.transform(x_train)
x_train_scale = pd.DataFrame(x_train_scale, columns= x.columns)
print(x_train_scale.shape)
x_train_scale.head()

(2800000, 54)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,0.561303,0.200000,0.223881,0.170428,0.394191,0.244120,0.740864,0.808696,0.718266,0.327421,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.441379,0.100000,0.149254,0.122328,0.449170,0.235191,0.817276,0.713043,0.414861,0.080417,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.419540,0.147727,0.268657,0.204869,0.408714,0.501698,0.863787,0.747826,0.486068,0.163950,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.451341,0.234091,0.283582,0.159145,0.360996,0.250031,0.465116,0.700000,0.359133,0.290628,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.462069,0.465909,0.537313,0.438836,0.362033,0.170545,0.840532,0.617391,0.866873,0.190676,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [241]:
x_test_scale = minmax_scaler.transform(x_test)
x_test_scale = pd.DataFrame(x_test_scale, columns= x.columns)
print(x_test_scale.shape)
x_test_scale.head()

(1200000, 54)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,0.360920,0.177273,0.358209,0.111045,0.501037,0.030436,0.780731,0.595652,0.603715,0.105705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.575096,0.247727,0.149254,0.166865,0.348548,0.225884,0.820598,0.721739,0.529412,0.183245,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.322605,0.829545,0.134328,0.201306,0.326763,0.448120,0.740864,0.704348,0.873065,0.180249,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.373180,0.850000,0.149254,0.059976,0.325726,0.219595,0.531561,0.730435,0.696594,0.300935,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.470881,0.277273,0.253731,0.140143,0.374481,0.138096,0.770764,0.747826,0.609907,0.546381,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [242]:
#Logistic Regression
lm = LogisticRegression()
lm.fit(x_train_scale, y_train)
y_pred = lm.predict(x_test_scale)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.9113598007990408

              precision    recall  f1-score   support

           1       0.90      0.92      0.91    440454
           2       0.94      0.95      0.94    678495
           3       0.86      0.81      0.83     58765
           4       0.00      0.00      0.00       110
           6       0.36      0.24      0.29      3437
           7       0.50      0.19      0.28     18739

    accuracy                           0.92   1200000
   macro avg       0.59      0.52      0.54   1200000
weighted avg       0.91      0.92      0.91   1200000

In [243]:
#Decision Tree#
clf = DecisionTreeClassifier()
clf = clf.fit(x_train_scale,y_train)
y_pred = clf.predict(x_test_scale)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.9425470159066333

              precision    recall  f1-score   support

           1       0.95      0.94      0.94    440454
           2       0.96      0.96      0.96    678495
           3       0.84      0.84      0.84     58765
           4       0.22      0.25      0.24       110
           6       0.50      0.52      0.51      3437
           7       0.72      0.72      0.72     18739

    accuracy                           0.94   1200000
   macro avg       0.70      0.71      0.70   1200000
weighted avg       0.94      0.94      0.94   1200000

In [244]:
#Random Forest
rf = RandomForestClassifier()
rf.fit(x_train_scale, y_train)
y_pred = rf.predict(x_test_scale)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.9563374231547223

              precision    recall  f1-score   support

           1       0.95      0.96      0.96    440454
           2       0.97      0.97      0.97    678495
           3       0.90      0.85      0.88     58765
           4       0.60      0.03      0.05       110
           6       0.80      0.31      0.45      3437
           7       0.89      0.60      0.72     18739

    accuracy                           0.96   1200000
   macro avg       0.85      0.62      0.67   1200000
weighted avg       0.96      0.96      0.96   1200000

In [245]:
#AdaBoost#
AdaBoost = AdaBoostClassifier()
AdaBoost.fit(x_train_scale,y_train)
y_pred=AdaBoost.predict(x_test_scale)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.8156330206141489

              precision    recall  f1-score   support

           1       0.85      0.97      0.91    440454
           2       0.89      0.92      0.90    678495
           3       0.00      0.00      0.00     58765
           4       0.00      0.00      0.00       110
           6       0.00      0.00      0.00      3437
           7       0.00      0.00      0.00     18739

    accuracy                           0.87   1200000
   macro avg       0.29      0.31      0.30   1200000
weighted avg       0.82      0.87      0.84   1200000

In [ ]:
#4-AFTER NORMALIZATION AND FEATURE SELECTION PROCESSES

In [246]:
#There are lots of features. Probably many of them doesn't have valuable information for a model. Let's decrease it

In [247]:
#Feature Selector didn't worked as above. We manually try to decrease the number of features

In [248]:
#Variance threshold
#We can elimate features by looking at their variance threshold. Example below eliminates features with 
#only 1 unique value

In [249]:
x_train_scale
x_test_scale
y_train
y_test

         Cover_Type
3072928           2
560206            1
2026981           2
3331817           2
271198            2
...             ...
964355            2
3914750           1
702606            1
603245            2
316493            2

[1200000 rows x 1 columns]

In [250]:
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold()
print("Original feature shape:", x_train_scale.shape)
select = selector.fit(x_train_scale)
x_train_new = select.transform(x_train_scale)
x_test_new = select.transform(x_test_scale)

print("Transformed feature shape:", x_train_new.shape)

Original feature shape: (2800000, 54)
Transformed feature shape: (2800000, 52)

In [251]:
#Univariate feature selection
# Next we are going to use f_classif test
#The f_classif test is based on the Analysis of Variance (ANOVA) statistical test which compares the means of a 
#number of groups, or in our case features, and determines whether any of those means are statistically
#significant from one another. (the default number of feature is 10)

In [252]:
from sklearn.feature_selection import SelectKBest

selector = SelectKBest(k=15)

print("Original feature shape:", x_train_new.shape)

select = selector.fit(x_train_new,y_train)
x_train_new2 = select.transform(x_train_new)
x_test_new2 = select.transform(x_test_new)

print("Transformed feature shape:", x_train_new2.shape)

Original feature shape: (2800000, 52)
Transformed feature shape: (2800000, 15)

In [253]:
#Logistic Regression
lm = LogisticRegression()
lm.fit(x_train_new2, y_train)
y_pred = lm.predict(x_test_new2)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.8944882698883516

              precision    recall  f1-score   support

           1       0.89      0.92      0.91    440454
           2       0.92      0.94      0.93    678495
           3       0.76      0.58      0.66     58765
           4       0.00      0.00      0.00       110
           6       0.33      0.21      0.25      3437
           7       0.54      0.18      0.27     18739

    accuracy                           0.90   1200000
   macro avg       0.57      0.47      0.50   1200000
weighted avg       0.89      0.90      0.90   1200000

In [254]:
#Decision Tree#
clf = DecisionTreeClassifier()
clf = clf.fit(x_train_new2,y_train)
y_pred = clf.predict(x_test_new2)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.9055444485032201

              precision    recall  f1-score   support

           1       0.92      0.92      0.92    440454
           2       0.93      0.93      0.93    678495
           3       0.65      0.65      0.65     58765
           4       0.09      0.10      0.09       110
           6       0.40      0.41      0.40      3437
           7       0.54      0.57      0.55     18739

    accuracy                           0.91   1200000
   macro avg       0.59      0.60      0.59   1200000
weighted avg       0.91      0.91      0.91   1200000

In [255]:
#Random Forest
rf = RandomForestClassifier()
rf.fit(x_train_new2, y_train)
y_pred = rf.predict(x_test_new2)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.9298428150868121

              precision    recall  f1-score   support

           1       0.94      0.95      0.95    440454
           2       0.95      0.95      0.95    678495
           3       0.73      0.69      0.71     58765
           4       0.50      0.03      0.05       110
           6       0.64      0.33      0.44      3437
           7       0.86      0.54      0.66     18739

    accuracy                           0.93   1200000
   macro avg       0.77      0.58      0.63   1200000
weighted avg       0.93      0.93      0.93   1200000

In [256]:
#AdaBoost#
AdaBoost = AdaBoostClassifier()
AdaBoost.fit(x_train_new2,y_train)
y_pred=AdaBoost.predict(x_test_new2)
print('Test Set Weighted Accuracy:',classification_report(y_test, y_pred, output_dict=True)['weighted avg']["precision"])
print(" ")
print(classification_report(y_test, y_pred))

Test Set Weighted Accuracy: 0.8156330206141489

              precision    recall  f1-score   support

           1       0.85      0.97      0.91    440454
           2       0.89      0.92      0.90    678495
           3       0.00      0.00      0.00     58765
           4       0.00      0.00      0.00       110
           6       0.00      0.00      0.00      3437
           7       0.00      0.00      0.00     18739

    accuracy                           0.87   1200000
   macro avg       0.29      0.31      0.30   1200000
weighted avg       0.82      0.87      0.84   1200000

In [ ]:
#5-DO HYPER PARAMETER SELECTION BY USING THE BEST SUBSET&MODEL

In [224]:
#Random Forest after StandardScaler gave the best accuracy score. Now we are going to do hyper parameter selection over it

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2021)

In [17]:
standard_scaler = StandardScaler().fit(x_train)

In [18]:
x_train_scale = standard_scaler.transform(x_train)
x_train_scale = pd.DataFrame(x_train_scale, columns= x.columns)
print(x_train_scale.shape)
x_train_scale.head()

(2800000, 54)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,0.891534,-0.877831,-0.362642,-0.292574,0.166649,-0.085948,0.233007,0.626759,0.919316,0.780481,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864
1,-0.191106,-1.278024,-0.947704,-0.650170,0.943800,-0.139902,0.980243,-0.362936,-1.323418,-1.046736,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864
2,-0.388264,-1.087023,-0.011605,-0.036518,0.371934,1.470337,1.435083,-0.003047,-0.797062,-0.428798,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,4.952563,-0.180864
3,-0.101174,-0.741402,0.105408,-0.376454,-0.302574,-0.050233,-2.463542,-0.497894,-1.735349,0.508304,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,4.952563,-0.180864
4,-0.004325,0.186317,2.094618,1.702898,-0.287911,-0.530493,1.207663,-1.352630,2.017798,-0.231094,...,-0.168369,5.063148,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,4.952563,-0.180864

In [19]:
x_test_scale = standard_scaler.transform(x_test)
x_test_scale = pd.DataFrame(x_test_scale, columns= x.columns)
print(x_test_scale.shape)
x_test_scale.head()

(1200000, 54)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,-0.917478,-0.968784,0.690469,-0.734050,1.676961,-1.377027,0.622869,-1.577561,0.072569,-0.859671,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864
1,1.016055,-0.686830,-0.947704,-0.319062,-0.478533,-0.196135,1.012732,-0.272964,-0.476672,-0.286061,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,4.952563,-0.180864
2,-1.263369,1.641562,-1.064716,-0.063006,-0.786460,1.146618,0.233007,-0.452908,2.063568,-0.308225,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864
3,-0.806793,1.723420,-0.947704,-1.113720,-0.801123,-0.234130,-1.813772,-0.182991,0.759121,0.584549,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864
4,0.075230,-0.568592,-0.128617,-0.517727,-0.111952,-0.726548,0.525404,-0.003047,0.118339,2.400241,...,-0.168369,-0.197506,-0.197927,-0.110085,-0.127837,-0.104062,-0.111214,-0.205784,-0.201916,-0.180864

In [28]:
from sklearn.model_selection import RandomizedSearchCV
from pprint import pprint

In [29]:
rf = RandomForestClassifier()
rf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [30]:
criterion = ["gini", "entropy"]

In [31]:
max_depth=["None",2,4,6,8]

In [32]:
min_samples_split =[int(x) for x in np.linspace(start=2,stop=10,num=8)]

In [33]:
min_samples_leaf= [int(x) for x in np.linspace(1,5,num=4)]

In [34]:
n_estimators =[75,100,125]

In [35]:
random_grid = {'criterion':criterion,'max_depth':max_depth,'min_samples_split':min_samples_split,'min_samples_leaf':min_samples_leaf,'n_estimators': n_estimators}

In [36]:
pprint(random_grid)

{'criterion': ['gini', 'entropy'],
 'max_depth': ['None', 2, 4, 6, 8],
 'min_samples_leaf': [1, 2, 3, 5],
 'min_samples_split': [2, 3, 4, 5, 6, 7, 8, 10],
 'n_estimators': [75, 100, 125]}

In [37]:
x_train_scale
x_test_scale
y_train
y_test

         Cover_Type
3072928           2
560206            1
2026981           2
3331817           2
271198            2
...             ...
964355            2
3914750           1
702606            1
603245            2
316493            2

[1200000 rows x 1 columns]

In [38]:
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid,n_iter=30,
                               cv = 5, random_state=2022)

In [39]:
rf_random.fit(x_train_scale,y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=30,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': ['None', 2, 4, 6, 8],
                                        'min_samples_leaf': [1, 2, 3, 5],
                                        'min_samples_split': [2, 3, 4, 5, 6, 7,
                                                              8, 10],
                                        'n_estimators': [75, 100, 125]},
                   random_state=2022)

In [40]:
rf_random.best_params_

{'n_estimators': 100,
 'min_samples_split': 3,
 'min_samples_leaf': 3,
 'max_depth': 8,
 'criterion': 'gini'}

In [41]:
rf_random.best_estimator_

RandomForestClassifier(max_depth=8, min_samples_leaf=3, min_samples_split=3)

In [42]:
y_predict = rf_random.best_estimator_.predict(x_test_scale)

In [43]:
print(cm(y_test, y_predict))

[[422141  18313      0      0      0      0]
 [ 34455 643233    807      0      0      0]
 [     0  36150  22615      0      0      0]
 [     0      0    110      0      0      0]
 [     0    838   2599      0      0      0]
 [ 18709     30      0      0      0      0]]

In [44]:
print("Accuracy:",metrics.accuracy_score(y_test, y_predict))

Accuracy: 0.9066575

In [45]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           1       0.89      0.96      0.92    440454
           2       0.92      0.95      0.93    678495
           3       0.87      0.38      0.53     58765
           4       0.00      0.00      0.00       110
           6       0.00      0.00      0.00      3437
           7       0.00      0.00      0.00     18739

    accuracy                           0.91   1200000
   macro avg       0.45      0.38      0.40   1200000
weighted avg       0.89      0.91      0.89   1200000

In [ ]:
#Grid Search didn't improve our accuracy, on the contrary it decreased it. So we are going to use default Random
#Forest hyper parameters to predict test data

In [20]:
x.shape

(4000000, 54)

In [21]:
y.shape

(4000000, 1)

In [40]:
df_test = pd.read_csv("Desktop/AI_Works/Kaggle/Tabular/test.csv")

In [24]:
df_test.shape

(1000000, 55)

In [41]:
df_test_id = df_test["Id"]

In [29]:
df_test.drop(columns=["Id"],inplace=True)

In [15]:
from sklearn.preprocessing import StandardScaler

In [32]:
standard_scaler = StandardScaler().fit(x)

In [34]:
x_scale = standard_scaler.transform(x)
x_scale = pd.DataFrame(x_scale, columns= x.columns)
print(x_scale.shape)
x_scale.head()

(4000000, 54)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,0.722400,-1.014774,-0.830439,-1.065177,-0.566768,1.142708,-0.189777,0.581997,1.194297,2.919073,...,-0.168138,-0.197282,-0.198261,-0.110185,-0.127732,-0.104061,-0.111168,-0.206113,-0.202094,-0.180696
1,0.158480,0.276592,-1.181450,0.038334,-0.332219,1.142708,0.687987,0.851886,-0.796612,3.406827,...,-0.168138,-0.197282,-0.198261,-0.110185,-0.127732,-0.104061,-0.111168,-0.206113,-0.202094,-0.180696
2,0.435250,-1.260315,-0.947443,0.351731,-0.214944,0.872111,-0.124758,0.581997,-0.087208,3.270256,...,-0.168138,-0.197282,-0.198261,-0.110185,-0.127732,-0.104061,-0.111168,-0.206113,-0.202094,-0.180696
3,0.144641,1.131439,-0.245420,-0.350102,-0.522790,0.963324,-0.157268,0.761923,0.347588,1.139212,...,-0.168138,-0.197282,-0.198261,-0.110185,-0.127732,-0.104061,-0.111168,-0.206113,-0.202094,-0.180696
4,-0.256676,0.312968,-0.245420,-0.023463,-0.434834,0.873632,0.622968,0.447052,0.301820,0.940562,...,-0.168138,-0.197282,-0.198261,-0.110185,-0.127732,-0.104061,-0.111168,-0.206113,-0.202094,-0.180696

In [35]:
df_test_scale = standard_scaler.transform(df_test)
df_test_scale = pd.DataFrame(df_test_scale, columns= x.columns)
print(df_test_scale.shape)
df_test_scale.head()

(1000000, 54)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,-0.751403,-0.669197,0.573607,0.466496,0.532682,1.016531,0.200340,-0.362616,1.240065,0.310029,...,-0.168138,-0.197282,-0.198261,-0.110185,-0.127732,-0.104061,-0.111168,-0.206113,-0.202094,-0.180696
1,-0.533446,0.012862,-0.479427,-0.032291,-0.185626,-1.118600,0.232850,0.761923,0.164516,0.865182,...,-0.168138,-0.197282,-0.198261,-0.110185,-0.127732,-0.104061,-0.111168,-0.206113,-0.202094,-0.180696
2,-0.111371,-0.860174,0.456603,-0.950412,-0.112329,-0.695223,-0.319817,-0.182690,0.507776,0.196515,...,-0.168138,-0.197282,5.043859,-0.110185,-0.127732,-0.104061,-0.111168,-0.206113,-0.202094,-0.180696
3,-0.187483,-0.296338,-1.064446,-0.500179,1.207011,0.280751,0.720497,0.851886,0.027212,-0.642423,...,-0.168138,-0.197282,-0.198261,-0.110185,-0.127732,-0.104061,-0.111168,-0.206113,-0.202094,-0.180696
4,-1.003956,-1.287598,-1.298454,-1.029864,0.825868,1.385182,0.037791,-0.002764,2.018121,-1.020211,...,-0.168138,-0.197282,-0.198261,-0.110185,-0.127732,-0.104061,-0.111168,-0.206113,-0.202094,-0.180696

In [36]:
#Random Forest
rf = RandomForestClassifier()
rf.fit(x_scale, y)

In [96]:
test_pred = rf.predict(df_test_scale)

In [97]:
type(test_pred)

numpy.ndarray

In [98]:
test_pred = pd.DataFrame(test_pred)

In [44]:
type(df_test_id)

pandas.core.series.Series

In [46]:
df_test_id = df_test_id.to_frame()

In [99]:
test = pd.concat([df_test_id, test_pred], axis=1, sort=False)

In [100]:
test.head()

        Id  0
0  4000000  2
1  4000001  2
2  4000002  2
3  4000003  2
4  4000004  2

In [101]:
test.rename(columns={0: "Cover_Type"},inplace=True)

In [102]:
test.to_csv("kaggle_tabular_submission.csv",index=False)

In [ ]:
#After uploading the file on Kaggle Competition, I got 0.9505 score which placed my rank around 700th-800th
#among 1200 participants